---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react
    service: react
  name: react-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react
      service: react
  template:
    metadata:
      labels:
        app: react
        service: react
    spec:
      containers:
        -
          image: "docker.io/yukesh/react:latest"
          name: react-service
          ports:
            -
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: react
  name: react-service
spec:
  ports:
    -
      name: react-port
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: react
    service: React
